---
title: "PUDA2022: Discovering clustering patterns"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(dplyr)
library(shiny)

load("clustersData.RData")
```


Distribución Económica
=======================================================================
Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = "modulo_",
            label =  "Modulo",
            choices = unique(mEcon$modulo),
            #choices = c("Laundry","BodyWashing","Toilet Use","Hand Washing",
            #            "Brushing Teeth","Dishwashing"),
            selected = "Laundry")

```

Column {data-width=450}
-----------------------------------------------------------------------

```{r}
##preparamos los datos

m_economic_contribucion_r <- reactive({mEcon %>% filter(modulo==input$modulo_) %>% group_by(cluster,`V9. PAGO_AGUA`) %>% summarise(Freq=n())})


m_economic_ingreso_r <- reactive({mEcon %>% filter(modulo==input$modulo_) %>% group_by(cluster,ClaseSocial) %>% summarise(Freq=n())})


```

### Cluster 1: Contribución al pago del agua

```{r}

renderPlotly({
  
  m_economic_contribucion<-m_economic_contribucion_r()
  
  ggplotly(
    
    m_economic_contribucion %>%
    filter(cluster==1) %>%
    ggplot(aes(x=`V9. PAGO_AGUA`,y=Freq))+
    geom_bar(stat='identity',fill="#7AC5CD")+
    labs(x = " ")
    
  )
  
})
```

### Cluster 1: Clase social por ingreso del hogar

```{r}

renderPlotly({
  
  #m_economic_ingreso<-m_economic_ingreso_r()
  
  ggplotly(
    
    m_economic_ingreso_r() %>%
      filter(cluster==1) %>%
      ggplot(aes(x=ClaseSocial,y=Freq))+
      geom_bar(stat='identity',fill="#7AC5CD")+
      labs(x = " ")
    
  )
  
})




```

Column {data-width=450}
-----------------------------------------------------------------------

### Cluster 2: Contribución al pago del agua

```{r}

renderPlotly({
  
  m_economic_contribucion<-m_economic_contribucion_r()
  
  ggplotly(
    
    m_economic_contribucion %>%
    filter(cluster==2) %>%
    ggplot(aes(x=`V9. PAGO_AGUA`,y=Freq))+
    geom_bar(stat='identity',fill="#A2CD5A")+
    labs(x = " ")
    
  )
  
})


```


### Cluster 2: Clase social por ingreso del hogar

```{r}

renderPlotly({
  
  #m_economic_ingreso<-m_economic_ingreso_r()
  
  ggplotly(
    
    m_economic_ingreso_r() %>%
      filter(cluster==2) %>%
      ggplot(aes(x=ClaseSocial,y=Freq))+
      geom_bar(stat='identity',fill="#A2CD5A")+
      labs(x = " ")
    
  )
  
})


```

Column {data-width=450}
-----------------------------------------------------------------------

### Cluster 3: Contribución al pago del agua

```{r}

renderPlotly({
  
  m_economic_contribucion<-m_economic_contribucion_r()
  
  ggplotly(
    
    m_economic_contribucion %>%
    filter(cluster==3) %>%
    ggplot(aes(x=`V9. PAGO_AGUA`,y=Freq))+
    geom_bar(stat='identity',fill="#EE6363")+
    labs(x = " ")
    
  )
  
})


```

### Cluster 3: Clase social por ingreso del hogar

```{r}

renderPlotly({
  
  #m_economic_ingreso<-m_economic_ingreso_r()
  
  ggplotly(
    
    m_economic_ingreso_r() %>%
      filter(cluster==3) %>%
      ggplot(aes(x=ClaseSocial,y=Freq))+
      geom_bar(stat='identity',fill="#EE6363")+
      labs(x = " ")
    
  )
  
})



```
